// ─── Source Registry ─────────────────────────────────────────────────────────
// Central registry of every data source the platform uses.
// The methodology page auto-generates from this. SourceAttribution components
// read from this. Nothing renders without being traceable here.

export interface DataSource {
  id: string
  name: string
  url: string
  description: string
  type: "news" | "research" | "government" | "jobs" | "market" | "trends" | "registry" | "talent" | "startup" | "benchmark" | "community" | "regulatory"
  refreshInterval: string
  clientFile: string
  dataScope: "national" | "provincial" | "both"
  reliability: "primary" | "aggregated" | "community"
  fetchMethod: "rss" | "api" | "scrape" | "manual"
}

export const SOURCES: DataSource[] = [
  {
    id: "rss-news",
    name: "Canadian News Feeds",
    url: "https://news.google.com",
    description: "AI-related news from Google News, BetaKit, and CBC Technology RSS feeds",
    type: "news",
    refreshInterval: "6h",
    clientFile: "rss-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "rss",
  },
  {
    id: "arxiv",
    name: "arXiv.org",
    url: "https://arxiv.org",
    description: "Pre-print research papers in AI and machine learning with Canadian-affiliated authors",
    type: "research",
    refreshInterval: "12h",
    clientFile: "arxiv-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "openparliament",
    name: "OpenParliament.ca",
    url: "https://openparliament.ca",
    description: "AI mentions in the federal House of Commons (Hansard). Federal Parliament only — does not cover Senate or provincial/territorial legislatures.",
    type: "government",
    refreshInterval: "24h",
    clientFile: "parliament-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "google-trends",
    name: "Google Trends",
    url: "https://trends.google.com",
    description: "Search interest for AI-related terms across Canadian provinces",
    type: "trends",
    refreshInterval: "12h",
    clientFile: "trends-regional-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "api",
  },
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    description: "Trending open-source AI repositories and Canadian developer activity",
    type: "research",
    refreshInterval: "12h",
    clientFile: "github-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "jobs",
    name: "Government of Canada Job Bank",
    url: "https://open.canada.ca/data/en/dataset/ea639e28-c0fc-48bf-b5dd-b8899bd43072",
    description: "Monthly AI job postings from Canada's National Job Bank open data (no API key required)",
    type: "jobs",
    refreshInterval: "24h",
    clientFile: "jobs-client.ts",
    dataScope: "both",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "stocks",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com",
    description: "Stock performance for Canadian AI-related public companies",
    type: "market",
    refreshInterval: "6h",
    clientFile: "stocks-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co",
    description: "AI model repository activity and Canadian-affiliated model releases",
    type: "research",
    refreshInterval: "24h",
    clientFile: "huggingface-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "epoch-ai",
    name: "Epoch AI",
    url: "https://epochai.org",
    description: "AI model benchmarks and compute trend data",
    type: "research",
    refreshInterval: "weekly",
    clientFile: "epoch-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "alliance-compute",
    name: "Digital Research Alliance of Canada",
    url: "https://alliancecan.ca",
    description: "National research compute cluster status and availability",
    type: "research",
    refreshInterval: "6h",
    clientFile: "alliance-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "statcan",
    name: "Statistics Canada",
    url: "https://www.statcan.gc.ca",
    description: "Labour force and economic data related to AI-sector employment",
    type: "registry",
    refreshInterval: "weekly",
    clientFile: "statscan-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "openalex",
    name: "OpenAlex",
    url: "https://openalex.org",
    description: "Open scholarly metadata for AI-related publications by Canadian researchers",
    type: "research",
    refreshInterval: "12h",
    clientFile: "research-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "gov-ai-registry",
    name: "Government of Canada AI Registry",
    url: "https://open.canada.ca/data/en/dataset/fcbc0200-79ba-4fa4-94a6-00e32facea6b",
    description: "Federal inventory of AI and automated decision systems in government use",
    type: "government",
    refreshInterval: "weekly",
    clientFile: "gov-ai-registry-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "oecd",
    name: "OECD AI Observatory",
    url: "https://oecd.ai",
    description: "AI publications and policy tracker comparing Canada with peer nations",
    type: "research",
    refreshInterval: "weekly",
    clientFile: "oecd-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  // ─── New Data Sources (Comprehensive Expansion) ─────────────────────────────
  {
    id: "ircc-immigration",
    name: "IRCC Open Data",
    url: "https://open.canada.ca",
    description: "Tech work permit and immigration data from Immigration, Refugees and Citizenship Canada",
    type: "talent",
    refreshInterval: "24h",
    clientFile: "ircc-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "nserc-grants",
    name: "NSERC Open Data",
    url: "https://open.canada.ca",
    description: "Discovery Grant awards for AI and machine learning research at Canadian universities",
    type: "talent",
    refreshInterval: "24h",
    clientFile: "nserc-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "university-programs",
    name: "Canadian University Programs",
    url: "https://www.univcan.ca",
    description: "Graduate and undergraduate AI, ML, and data science programs at Canadian universities",
    type: "talent",
    refreshInterval: "quarterly",
    clientFile: "university-programs-data.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "manual",
  },
  {
    id: "legisinfo",
    name: "LEGISinfo",
    url: "https://www.parl.ca/legisinfo/",
    description: "AI-related bills and legislation in the Parliament of Canada",
    type: "regulatory",
    refreshInterval: "12h",
    clientFile: "legisinfo-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
  },
  {
    id: "opc-privacy",
    name: "Office of the Privacy Commissioner",
    url: "https://www.priv.gc.ca",
    description: "AI-related privacy findings, guidance, and reports from the OPC",
    type: "regulatory",
    refreshInterval: "24h",
    clientFile: "opc-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "rss",
  },
  {
    id: "provincial-regulation",
    name: "Provincial AI Regulation",
    url: "https://www.canada.ca/en/government/system/digital-government.html",
    description: "Provincial and federal AI regulatory frameworks, directives, and guidelines",
    type: "regulatory",
    refreshInterval: "quarterly",
    clientFile: "provincial-regulation-data.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "manual",
  },
  {
    id: "global-ai-index",
    name: "Global AI Index",
    url: "https://aiindex.stanford.edu",
    description: "International AI rankings comparing Canada across talent, research, and commercial dimensions",
    type: "benchmark",
    refreshInterval: "annually",
    clientFile: "global-ai-index-data.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "manual",
  },
  {
    id: "wipo-patents",
    name: "WIPO IP Statistics",
    url: "https://www3.wipo.int/ipstats/",
    description: "AI patent filings and grants by country from the World Intellectual Property Organization",
    type: "benchmark",
    refreshInterval: "annually",
    clientFile: "wipo-patents-data.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "manual",
  },
  {
    id: "startups",
    name: "Canadian AI Startups",
    url: "https://betakit.com",
    description: "Curated directory of notable Canadian AI startups with funding signals from news",
    type: "startup",
    refreshInterval: "6h",
    clientFile: "startup-signals-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "rss",
  },
  {
    id: "ai-events",
    name: "Canadian AI Events",
    url: "https://cifar.ca",
    description: "Conferences, meetups, and public consultations across Canada's AI community",
    type: "community",
    refreshInterval: "quarterly",
    clientFile: "events-data.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "manual",
  },
]

export function getSourceById(id: string): DataSource | undefined {
  return SOURCES.find((s) => s.id === id)
}

export function getSourcesByType(type: DataSource["type"]): DataSource[] {
  return SOURCES.filter((s) => s.type === type)
}
