// Central registry of actively rendered data sources.
// Methodology and SourceAttribution read from this file, so every visible
// source-backed surface should be traceable here.

export interface DataSource {
  id: string
  name: string
  url: string
  description: string
  type: "news" | "research" | "government" | "jobs" | "registry" | "startup" | "benchmark" | "regulatory" | "procurement" | "market"
  refreshInterval: string
  clientFile: string
  dataScope: "national" | "provincial" | "both"
  reliability: "primary" | "aggregated" | "community"
  fetchMethod: "rss" | "api" | "scrape" | "manual"
  sourceStatus: "live" | "mixed" | "curated"
  evidenceRole: "adoption-rate" | "public-sector-system" | "demand-signal" | "proxy-signal" | "context" | "source-feed"
}

export const SOURCES: DataSource[] = [
  {
    id: "rss-news",
    name: "Canadian News Feeds",
    url: "https://news.google.com",
    description: "AI-related Canadian news from Google News, BetaKit, CBC Technology, and province-targeted RSS queries.",
    type: "news",
    refreshInterval: "6h",
    clientFile: "rss-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "rss",
    sourceStatus: "live",
    evidenceRole: "source-feed",
  },
  {
    id: "arxiv",
    name: "arXiv.org",
    url: "https://arxiv.org",
    description: "Pre-print research papers in AI and machine learning with Canadian-affiliated authors.",
    type: "research",
    refreshInterval: "12h",
    clientFile: "arxiv-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "openalex",
    name: "OpenAlex",
    url: "https://openalex.org",
    description: "Open scholarly metadata for AI-related publications by Canadian researchers.",
    type: "research",
    refreshInterval: "12h",
    clientFile: "research-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "nserc",
    name: "NSERC Awards Database",
    url: "https://www.nserc-crsng.gc.ca/ase-oro/index_eng.asp",
    description: "Canadian research grants related to AI, machine learning, robotics, and data science.",
    type: "research",
    refreshInterval: "24h",
    clientFile: "nserc-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "alliance-compute",
    name: "Digital Research Alliance of Canada",
    url: "https://alliancecan.ca",
    description: "National research computing systems and institute compute updates.",
    type: "research",
    refreshInterval: "12h",
    clientFile: "alliance-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "scrape",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "statcan",
    name: "Statistics Canada macro indicators",
    url: "https://www.statcan.gc.ca",
    description: "Labour force, CPI, and GDP context indicators from Statistics Canada WDS.",
    type: "registry",
    refreshInterval: "weekly",
    clientFile: "statscan-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "statcan-ai-adoption",
    name: "Statistics Canada AI adoption tables",
    url: "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3310100401",
    description: "Official Canadian Survey on Business Conditions tables for actual AI use, planned AI use, employment impact, and operational changes.",
    type: "registry",
    refreshInterval: "6h",
    clientFile: "statcan-sdmx-client.ts",
    dataScope: "both",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "adoption-rate",
  },
  {
    id: "jobs",
    name: "Government of Canada Job Bank",
    url: "https://open.canada.ca/data/en/dataset/ea639e28-c0fc-48bf-b5dd-b8899bd43072",
    description: "Monthly AI-related job postings from Canada's National Job Bank open data.",
    type: "jobs",
    refreshInterval: "24h",
    clientFile: "jobs-client.ts",
    dataScope: "both",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "proxy-signal",
  },
  {
    id: "openparliament",
    name: "OpenParliament.ca",
    url: "https://openparliament.ca",
    description: "AI mentions in federal House of Commons debates.",
    type: "government",
    refreshInterval: "24h",
    clientFile: "parliament-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "legisinfo",
    name: "LEGISinfo",
    url: "https://www.parl.ca/legisinfo/",
    description: "AI-related bills and legislation in the Parliament of Canada.",
    type: "regulatory",
    refreshInterval: "12h",
    clientFile: "legisinfo-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "provincial-regulation",
    name: "Provincial AI Regulation",
    url: "https://www.canada.ca/en/government/system/digital-government.html",
    description: "Curated provincial and federal AI regulatory frameworks, directives, and guidelines.",
    type: "regulatory",
    refreshInterval: "quarterly",
    clientFile: "provincial-regulation-data.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "manual",
    sourceStatus: "curated",
    evidenceRole: "context",
  },
  {
    id: "gov-ai-register",
    name: "Government of Canada AI Register",
    url: "https://open.canada.ca/data/en/dataset/fcbc0200-79ba-4fa4-94a6-00e32facea6b",
    description: "Federal public-sector AI system inventory discovered dynamically through Open Canada CKAN.",
    type: "government",
    refreshInterval: "12h",
    clientFile: "gov-ai-registry-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "public-sector-system",
  },
  {
    id: "canadabuys-tenders",
    name: "CanadaBuys tender notices",
    url: "https://open.canada.ca/data/en/dataset/6abd20d4-7a1c-4b38-baa2-9525d0bb2fd2",
    description: "Open tender notices classified as AI, automation, cloud, or data demand signals.",
    type: "procurement",
    refreshInterval: "6h",
    clientFile: "procurement-demand-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "demand-signal",
  },
  {
    id: "contracts-over-10k",
    name: "Contracts over $10,000",
    url: "https://open.canada.ca/data/en/dataset/d8f85d91-7dec-4fd1-8055-483b77225d8b/resource/fac950c0-00d5-4ec1-a4d3-9cbebf98a305",
    description: "Recent federal contract samples classified as procurement demand signals, not adoption rates.",
    type: "procurement",
    refreshInterval: "12h",
    clientFile: "procurement-demand-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "mixed",
    evidenceRole: "demand-signal",
  },
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    description: "Canadian AI open-source repository activity used as an ecosystem proxy signal.",
    type: "startup",
    refreshInterval: "12h",
    clientFile: "github-client.ts",
    dataScope: "national",
    reliability: "community",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "proxy-signal",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co",
    description: "Canadian model and dataset releases used as an ecosystem proxy signal.",
    type: "startup",
    refreshInterval: "12h",
    clientFile: "huggingface-client.ts",
    dataScope: "national",
    reliability: "community",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "proxy-signal",
  },
  {
    id: "startups",
    name: "Canadian AI Startups",
    url: "https://betakit.com",
    description: "Curated company directory with funding and product signals from news sources.",
    type: "startup",
    refreshInterval: "6h",
    clientFile: "startup-signals-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "rss",
    sourceStatus: "mixed",
    evidenceRole: "proxy-signal",
  },
  {
    id: "google-trends",
    name: "Google Trends",
    url: "https://trends.google.com",
    description: "Relative Canadian search interest in AI terms. Proxy signal only; not a direct adoption measure.",
    type: "market",
    refreshInterval: "6h",
    clientFile: "trends-client.ts",
    dataScope: "both",
    reliability: "aggregated",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "proxy-signal",
  },
  {
    id: "stocks",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com",
    description: "Delayed market quotes for Canadian AI-adjacent public companies. Context only, not investment advice.",
    type: "market",
    refreshInterval: "15m",
    clientFile: "stocks-client.ts",
    dataScope: "national",
    reliability: "aggregated",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "oecd",
    name: "OECD AI Policy Observatory",
    url: "https://oecd.ai",
    description: "International AI policy and skills context for Canada.",
    type: "benchmark",
    refreshInterval: "weekly",
    clientFile: "oecd-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "epoch-ai",
    name: "Epoch AI",
    url: "https://epoch.ai",
    description: "Frontier AI model and compute trend context.",
    type: "benchmark",
    refreshInterval: "12h",
    clientFile: "epoch-client.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "api",
    sourceStatus: "live",
    evidenceRole: "context",
  },
  {
    id: "global-ai-index",
    name: "Global AI rankings",
    url: "https://hai.stanford.edu/ai-index",
    description: "Annual global AI benchmarks used for broad international context.",
    type: "benchmark",
    refreshInterval: "annually",
    clientFile: "global-ai-index-data.ts",
    dataScope: "national",
    reliability: "primary",
    fetchMethod: "manual",
    sourceStatus: "curated",
    evidenceRole: "context",
  },
]

export function getSourceById(id: string): DataSource | undefined {
  return SOURCES.find((source) => source.id === id)
}

export function getSourcesByType(type: DataSource["type"]): DataSource[] {
  return SOURCES.filter((source) => source.type === type)
}
